// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumTest() {
    driver.get("https://www.google.com/search?q=javaguru&sca_esv=580414175&sxsrf=AM9HkKk3o1NAnr8_bd_8DWi7Iz643-GhYQ%3A1699435638783&source=hp&ei=dlRLZbfMLfKKxc8Pr5KPoAg&iflsig=AO6bgOgAAAAAZUtihtVHhtCW0aVJa_zJCCSL6tyFEXo5&ved=0ahUKEwi338OMi7SCAxVyRfEDHS_JA4QQ4dUDCAo&uact=5&oq=javaguru&gs_lp=Egdnd3Mtd2l6IghqYXZhZ3VydTIEECMYJzIFEAAYgAQyChAAGMsBGIAEGAoyBBAAGB4yAhAmSNA0UABYqCxwAHgAkAEAmAGyAaABlgmqAQMwLji4AQPIAQD4AQHCAgcQIxiKBRgnwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiABBixAxiDAcICCBAAGIAEGLEDwgIMECMYigUYExiABBgnwgIPEAAYgAQYsQMYgwEYChgBwgIFEC4YgATCAhEQLhiABBixAxiDARjHARivAcICCBAuGMsBGIAEwgIIEAAYywEYgAQ&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(904, 534));
    driver.findElement(By.cssSelector(".CCgQ5 > span")).click();
    driver.findElement(By.cssSelector(".single-hero-button > .pulse-button")).click();
    driver.findElement(By.name("form-name")).click();
    driver.findElement(By.name("form-name")).sendKeys("Nikita");
    driver.findElement(By.name("form-surname")).click();
    driver.findElement(By.name("form-surname")).sendKeys("Voronins");
    driver.findElement(By.name("form-email")).click();
    driver.findElement(By.name("form-email")).sendKeys("stowa.Voronin@gmail.com");
    driver.findElement(By.name("form-phone")).click();
    driver.findElement(By.name("form-phone")).sendKeys("33333444445");
    driver.findElement(By.name("form-message")).click();
    driver.findElement(By.name("form-message")).sendKeys("dsagasgsdgaqsdgasgasdgasdf");
    driver.findElement(By.cssSelector(".submit-button > .default-button")).click();
  }
}
